name: General
description: File an issue that is not covered by other issue templates
title: "[General]:"
labels: [general]

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this form!

- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: eg. email@example.com
  validations:
    required: false

- type: textarea
  id: problem-description
  attributes:
    label: Problem Description
    description: Please describe the problem you encountered in detail
  validations:
    required: true
