name: Generate Excel file on release
run-name: Generating Excel file for release ${{github.ref_name}}
on:
  release:
    types: [released]
jobs:
  Generate-Excel-File:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: check out repository code
        uses: actions/checkout@v4
        with:
          ref: main
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Remove previous output file
        run: rm ${{ github.workspace }}\output.xlsx
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install argparse
          pip install logging
          pip install pandas
          pip install openpyxl
      - name: execute py script
        run: python other/scripts/output_file_generator.py ${{ github.workspace }}/ -o ${{ github.workspace }}\output
      - name: commit files
        run: |
          git config --local user.email "federate-office@avl.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automatic creation of output.xlsx on release ${{github.ref_name}}"
          git push
      - run: echo "Job finished with status ${{ job.status }}."
