name: Run README Generator when pull request is merged to main branch

on:
   pull_request:
    types: [closed]
    branches: [ main ]
    
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python scripts/readme_generator.py

    - name: Possible Errors
      run: echo "If your github account was created before July 18, 2017, automatic creation of the README will not work. Please update the README maually by running the readme_generator.py file!"

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

    - name: Commit and push
      run: |
        git add .
        git commit -m "Automatic update of README.md on merge"
        git push